# Project
version=4.7.1
group=com.evandev.remi
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Reliable EMI
mod_author=evanbones
mod_id=remi
license=MIT
credits=ConcerroX, Kobber
description=A mod adding many configurable features to EMI!
minecraft_version_range=[1.21.1, 1.21.2)
neo_form_version=1.21.1-20240808.144430

# Parchment
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Dependencies
emi_version=1.1.24+1.21.1
mixinextras_version=0.5.0
modmenu_version=11.0.4
yacl_version=3.8.2+1.21.1

# Fabric
fabric_version=0.116.7+1.21.1
fabric_loader_version=0.18.3

# NeoForge
neoforge_version=21.1.199
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true