name: Bug Report
description: Create a bug report to help me improve EMI++ Backport.
labels: [ "bug" ]
body:
    -   type: textarea
        attributes:
            label: Describe the Bug
            description: A clear and concise description of what the bug is
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Reproduction Steps
            description: Tell me about the steps to reproduce the bug
            value: |
                1. 
                2. 
                3.
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Expected Result
            description: A clear and concise description of what you expected to happen
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Screenshots and Videos
            description: If applicable, add screenshots or videos to help explain your problem
        validations:
            required: false
    -   type: dropdown
        attributes:
            label: Mod Version
            description: The version of EMI++ Backport you were using
            options:
                - "1.1.4"
                - "1.1.3"
                - "1.1.2"
                - "1.1.1"
                - "1.1.0"
                - "1.0.0"
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Mod Loader
            description: Which mod loader were you using?
            options:
                - "Forge"
                - "Fabric"
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Other Mods / Modpack
            description: Please list other mods or the name of the modpack you are running.
        validations:
            required: false
    -   type: textarea
        attributes:
            label: Additional Context
            description: Attach crash reports or logs here (use mclo.gs or similar if long).
        validations:
            required: false
    -   type: markdown
        attributes:
            value: "Thank you for taking the time to fill out this bug report!"